# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Some of what I don't know
subtitle: Looking for CS ideas to build better software
description:
keywords:
author: Phil Allen
language:
timezone: Europe/London

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://philallen117.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: anodyne

theme_config:
  menu:
    Home: /
    Tags: /tags
    About: /about/index.html
  archive_font_awesome_icon_css: fas fa-calendar-alt
  about_widget_avatar_url: https://philallen117.github.io/img/phil-cartoon-6.jpeg
  about_widget_text: I am Phil Allen, a software architect based in Bristol, UK. I enjoy learning.
  comments_facebook: false
  default_post_icon: fas fa-angle-double-right
  default_post_title: Draft
  footer_about: "(c) Phil Allen, 2018, CC BY-SA 4.0"
  google_analytics: false # fix up later
  index_banner_text: Some of the things I don't know, yet
  index_banner_text_secondary: Exploring CS for better software
  index_font_awesome_icon_css: fas fa-angle-double-right
  logo_image_source: https://philallen117.github.io/img/bind-writing.svg
  twitter_handle: "@philallen"
  social_platforms:
    - url: https://twitter.com/philallen?lang=en
      fa_icon: fa-twitter
    - url: https://www.linkedin.com/in/phillipgallen
      fa_icon: fa-linkedin
    - url: https://github.com/philallen117
      fa_icon: fa-github

  # theme.comments && theme.comments.disqus_shortname
  # faceboojk stuff in header - cut out properly? default of theme.comments?

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
